databricks/spark-xml

- .travis.yml
- README.md
- build.sbt
- project/assembly.sbt
- project/build.properties
- project/plugins.sbt
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
CC @HyukjinKwon -- this might be a good prelude to further fixes and a new release. This should make sure Java 8, Spark 2.4 and Scala 2.12 work. Along the way I suggest we forget about Spark before 2.2. I updated plugins to match Spark for good measure.
> Fix minor issues to enable Scala 2.12, Spark 2.4 supports. Update plugins too

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtils.scala
Don't output XMLEvent.toString; doesn't work on for instance the woodstox parser, which renders `[STaX event #1]` etc. Only output tag events and use the tag name directly, and output Characters elements directly instead.
> Don't output XMLEvent.toString; doesn't work on for instance the woodstox parser

- README.md
- build.sbt
- src/main/scala/com/databricks/spark/xml/XmlReader.scala
- src/test/java/com/databricks/spark/xml/JavaXmlSuite.java
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Use SparkSession in favor of deprecated SQLContext in tests (deprecation warning), and add method that directly accepts SparkSession. Plus minor fixes elsewhere to the code that raise IJ warnings.
> Use SparkSession in favor of deprecated SQLContext in tests (deprecation warning)

- src/main/scala/com/databricks/spark/xml/XmlInputFormat.scala
- src/test/resources/self-closing-tag.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
This should supersede:
- https://github.com/databricks/spark-xml/pull/316
- https://github.com/databricks/spark-xml/pull/321
- https://github.com/databricks/spark-xml/pull/149
To make the fix, it seemed necessary to rewrite the logic in terms of characters, not bytes. Honestly I don't know why the original implementation worked in terms of bytes, even though I might have been part of it.
This does handle self-closing tags, but not nested copies of the same row tag. The latter is either something we need to drop or, will require another rewrite to handle sanely.
> Rewrite XMLInputFormat in terms of chars not bytes. Fix handling of self-closing tags

- README.md
Minor fixes to README; standardize showing .xml() in Scala, use short… format string "xml", add missing imports, use schema in SparkR exmaple
> Minor fixes to README; standardize showing .xml() in Scala, etc

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/resources/null-nested-struct-2.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
This is a rebase and modification of the fix at https://github.com/databricks/spark-xml/pull/326 which addressed https://github.com/databricks/spark-xml/issues/314 both from @elibus .
It's a behavior change but I think the behavior change is correct, and was only inadvertently introduced in https://github.com/databricks/spark-xml/pull/118
> Return Row of null instead of null for empty elements that are structs in schema

- build.sbt
- src/main/scala/com/databricks/spark/xml/XmlRelation.scala
We don't need to extend `TableScan` if it implements `PrunedScan`. See https://github.com/apache/spark/blob/5ad03607d1487e7ab3e3b6d00eef9c4028ed4975/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/DataSourceStrategy.scala#L271-L302
> Remove useless extending TableScan

- build.sbt
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/CompressionCodecs.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
More just kinda cleanup... in several places a function is defined that returns a function object, but is just invoked like a function. I think they can be simple methods?
> Define simple methods instead of function objects

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/TypeCast.scala
- src/test/scala/com/databricks/spark/xml/util/TypeCastSuite.scala
Added Support for supporting xsd boolean lexical literals 1, 0 along with true and false.
Added clause in the throws exception (in case of FAILFAST mode) to add root cause.
> Support Xml Boolean Lexical Literal 1 and 0 for boolean data type

- src/main/scala/com/databricks/spark/xml/XmlInputFormat.scala
- src/test/resources/nested-element-with-attributes-and-name-of-parent.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Fix for https://github.com/databricks/spark-xml/issues/373
> Fix for nested tag names with attributes bug

- README.md
- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/test/resources/textColumn.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
**Background**
Discussion of support all string type column inferring strategy.
Issues : https://github.com/databricks/spark-xml/issues/205
**Use case**
Want to use column inferring to take advantage of no predefined schema.
But want to treat every data as plain text instead of parsed one.
Ex: value “00010” will be inferred as long type and data becomes 10.
It’s not possible to recover data from 10 to “00010” during processing.
**Proposed Solution**
Add interface for custom column data type inferring strategy.
**Modification**
Add interface for column infer strategy.
Add new column infer strategy to treat every column as string.
Add unit test for default, all string infer strategy.
**Test result**
Pass scalastyle, all unit tests, local integration test.
Please let me know if there is any …
> Add support of custom column infer strategy #205

- README.md
There is a comment "At the moment, rows containing self closing xml tags are not supported." which may no longer be true as per... https://github.com/databricks/spark-xml/pull/303
> Self-closing tag support : no longer accurate

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/test/resources/processing.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Simply ignore processing instructions, or else it will cause schema inference and parsing to fail when included inside an element.
Closes #411
> Ignore processing instructions to fix errors caused by them

- src/main/scala/com/databricks/spark/xml/util/XmlFile.scala
Really simple change, but really important. The code clearly intends to output the XML for one row as the output record that is then written with TextOutputFormat. However, after writing, the `indentingXmlWriter`'s buffer may not be full, and the part that made it to `writer` is incomplete. The rest will be written with the next record, yes, but, TextOutputFormat will put its line separator between the output. This could land right in the middle of a tag or worse.
The tests passed without this change as it seems to only affect Hadoop 2.8 or so and later, probably because some defaults changed somewhere about buffers, etc. However, I think the theoretical issue still is there for all versions.
If I'm right, this fixes at least #338 and #414
> Flush indenting XML writer to make sure one element is written per 'line' in the Hadoop output

- .travis.yml
- README.md
- build.sbt
- project/assembly.sbt
- project/plugins.sbt
- Use latest Spark versions
- Enable mima again for 2.12
- Update version to 0.7.0
- Clarify support in docs
- Various plugin version updates
> Various updates for 0.7.0, including updating travis versions, plugin versions

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/test/resources/mixed_children.xml
- src/test/resources/mixed_children_2.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
(Don't merge this yet)
See https://github.com/databricks/spark-xml/issues/415 for a bug report. There are two issues:
1. We don't really handle mixed text / node children of elements, possibly by design
2. But, their presence in this example causes the rest of the normal XML to not be parsed correctly
We need to fix the second, I think, one way or the other. 
What about the first?
The conceptual issue is that an element may have character elements all over the place between its child nodes. What does that map to in a schema?
1. an array of strings under the same `_VALUE` element we use for the body of an element with attributes?
2. same, but one joined string?
3. same, but just the first string
Number 2 doesn't quite make sense as there's no conceptual reason to join them. Number 1 does, …
> Handle character elements mixed text/node elements

- .travis.yml
- build.sbt
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala
- src/main/scala/com/databricks/spark/xml/util/XmlFile.scala
This adds a test profile for Spark 3 and Java 11.
It switches to use the IndentingXMLStreamWriter from Glassfish instead of from the JDK, as it is no longer present in Java 9+.
> Support Java 11 / test vs Spark 3

- README.md
- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/main/scala/com/databricks/spark/xml/XmlReader.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/test/resources/basket.xml
- src/test/resources/basket.xsd
- src/test/resources/basket_invalid.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
This adds a new configuration `rowValidationXSDPath`, which gives a path to an XSD file. If specified, this is used to validate the XML of each row. If validation fails, the row is considered 'corrupt' and handled as usual.
This does not affect the schema inferred by or specified for XML parsing. It can be used for finer-grained validation beyond simple schema checking.
See https://github.com/databricks/spark-xml/issues/224 for some discussion.
One open question is: is a path to a file the best API? support general URIs?
> Add setting to validate rows against an XSD

- README.md
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/main/scala/com/databricks/spark/xml/util/ValidatorUtil.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
(@HyukjinKwon only if you care to review, no big deal)
I found after adding the XSD validation feature that creating the XSD schema can be expensive. It can refer to lots of external resources that take time to download, and are accessed repeatedly. Further, I realized that the existing solution won't work unless the XSD itself is available on executors, unless the XSD is already on an accessible distributed store.
I'd propose to cache the Schema, firstly, to avoid recomputing it for inference vs parsing and for every partition. I've also made it support files added by SparkContext.addFile
> Improve XSD validation: support files added via addFile(); cache Schema

- src/main/scala/com/databricks/spark/xml/XmlReader.scala
- src/main/scala/com/databricks/spark/xml/package.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
This change:
1. `def xmlDataset(spark: SparkSession, df: DataFrame):` -> `def xmlDataset(spark: SparkSession, ds: Dataset[String]):`
2. Adds a shortcut for it `spark.read.xml(xmlDataset: Dataset[String])`
This is similar with https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/DataFrameReader.scala#L506
> Add spark.read.xml(xmlDataset: Dataset[String])

- .travis.yml
- README.md
- build.sbt
- scalastyle-config.xml
- src/main/scala/com/databricks/spark/xml/XmlDataToCatalyst.scala
- src/main/scala/com/databricks/spark/xml/functions.scala
- src/main/scala/com/databricks/spark/xml/package.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtils.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
This is a continuation of https://github.com/databricks/spark-xml/pull/334/
This implements a `from_xml` expression that can turn an XML string column into a parsed structured column. It also opens up `inferSchema` for a `Dataset[String]` as a necessary support function.
The rest is really mild refactoring.
> from_xml and schema_for_xml support

- README.md
- build.sbt
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Add support for XSD validation (`rowValidationXSDPath`) when using functions like `from_xml`. 
Also, improve and clarify the semantics of parse mode when using `from_xml`. If the "corrupt record" column is not in the supplied schema, and parse mode is `PERMISSIVE`, then don't cause an error, but instead assume `DROPMALFORMED` mode, which results in a `null` value.
CC @HyukjinKwon purely FYI. No action needed.
> Add XSD validation to from_xml. Clarify semantics of parse mode for from_xml

- src/main/scala/com/databricks/spark/xml/XmlInputFormat.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/resources/unclosed_tag.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
See https://github.com/databricks/spark-xml/issues/436#issuecomment-585358369 for context. This stops silently swallowing unclosed tags at the end of input and instead propagates the remaining content for normal error handling.
Closes #436
> Don't silently swallow unclosed tag content; propagate for error handling instead

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/resources/whitespace_error.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Where a field has, say, type 'double', and the element value is just whitespace, it fails with a hard error instead of being a 'normal' parsing failure. See https://github.com/databricks/spark-xml/issues/446
This fixes it by actually trying to parse the whitespace as the desired type, to generate the normal failure. Otherwise the whitespace was returned to Spark as if it were a Double.
> Handle case of whitespace-only, numeric-primitive field correctly

- src/main/scala/com/databricks/spark/xml/util/TypeCast.scala
- src/test/scala/com/databricks/spark/xml/util/TypeCastSuite.scala
Hi,
Currently the parsing of Date and Timestamp types does not comply with the the XSD schema definition: https://www.w3.org/TR/xmlschema-2/#dateTime
This PR adds the official date and datetime parsing when using a user-defined schema.
> fix date and datetime parsing

- build.sbt
- src/main/scala/com/databricks/spark/xml/XmlDataToCatalyst.scala
- src/main/scala/com/databricks/spark/xml/XmlReader.scala
- src/main/scala/com/databricks/spark/xml/package.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala
- src/test/java/com/databricks/spark/xml/JavaXmlSuite.java
- src/test/scala/com/databricks/spark/xml/XmlPartitioningSuite.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
- src/test/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtilsSuite.scala
- src/test/scala/com/databricks/spark/xml/util/CompressionCodecsSuite.scala
- src/test/scala/com/databricks/spark/xml/util/TypeCastSuite.scala
- src/test/scala/com/databricks/spark/xml/util/XmlFileSuite.scala
Very minor code cleanup to avoid warnings.
Deprecate `XmlReader.withFailFast`, as it doesn't so much make sense when there is already a method to set mode. Also, the method previously ignored its argument; now it will unset the property if passed `false`.
> Minor cleanup, including deprecating unuseful withFailFast method

- .travis.yml
- README.md
- build.sbt
- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
Relates to #449 and @seddonm1 's gist.
Adds a basic XSDToSchema utility that can parse a Spark schema from _some_ XSDs, those defining a table-like schema with simple, complex and sequence types.
> XSD -> schema tool with a test

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/include-example/first.xsd
- src/test/resources/include-example/second.xsd
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
The current parser does not support specifying the base URI, as a consequence relative imports fail. 
In this PR:
- Set BaseURI when reading xsd schemas
> support include statement with relative path

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtils.scala
- src/test/resources/cars-attribute.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Resolves https://github.com/databricks/spark-xml/issues/375
When reconstructing the value of a string field, where the element's children are XML, the XML is parsed then reconstructed (TODO: maybe one day this can be avoided). Attributes aren't preserved. This puts them back.
> Preserve attributes when reconstructing string field from XML

- src/main/scala/com/databricks/spark/xml/XmlInputFormat.scala
See #450 
The idea here is that we have to account for exactly how much data has been read from the underlying split, but not yet evaluated. Buffering is the problem. Previously we accounted for data buffered in StreamDecoder's ByteBuffer. I think we may have to account for the fact that it reads 2 chars at a time, and so may have buffered one more.
It should be extremely rare that this causes a problem - it would have to have read a start `<` that is the final char in a split, and have no buffered last char. But it's possible and indeed see the issue above - in tens of millions of records it might happen.
I don't know if this is the solution, but an OK guess.
> Take into account StreamDecoder.hasLeftoverChar in trying to exactly always correctly determine how much has been read

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/catalog.xsd
- src/test/scala/com/databricks/spark/xml/TestUtils.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
Closes #474 
- Fixes how QNames were looked up from the schema - did not actually work before
- Attributes were not handled in most cases; now they are
- Nullability wasn't handled correctly in many cases according to minOccurs; now should be
- Refactored test code to share schema construction code
> Fix error in parsing XSD types; handle attributes on all elements; more correctly handle nullability in XSDs

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala
- src/test/scala/com/databricks/spark/xml/parsers/StaxXmlGeneratorSuite.scala
We are currently (https://github.com/databricks/spark-xml/blob/master/src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala#L79) relying on the default java.sql.Timestamp format (https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html#toString--) which formats timestamp objects in local time whereas the spec https://www.w3.org/TR/xmlschema-2/#dateTime indicates everything should be in UTC.
As the spec supports the inclusion of the timezone 'Z' we should be explicit so anyone manually reading a file can also understand the accurate timestamp.
See https://github.com/databricks/spark-xml/issues/485
> FIX #485 Fix Timestamp to conform to XML Spec

- README.md
Fundamentals for spark 3 have been in place since release of 0.6.x. This makes that support explicit in the README.
> explicitly state spark 3 support

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/twoelements.xsd
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
This relates to issue #484 
The XSD -> schema tool currently only pays attention to the first element in the XSD. There's no good reason not to allow multiple ones.
I also believe I fixed a possible bug in determining the element name.
> Allow multiple root elements in XSD

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/choice.xsd
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
Closes #490 
Because only one child of an xs:choice can actually appear, those fields should be inherently nullable always.
> Assume xs:choice elements are nullable

- .gitignore
- .travis.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
- scalastyle-config.xml
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala
- src/test/scala/com/databricks/spark/xml/parsers/StaxXmlGeneratorSuite.scala
Not sure why, but different classpath treatment during tests in sbt 1.3 makes Spark 2.x tests fail. 
Otherwise just fixing a breakage in master while updating to at least SBT 1.2.8
> Update to sbt 1.2.x (1.3+ not working yet); fix latent scalastyle issue

- README.md
- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/xsany.xsd
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
See https://github.com/databricks/spark-xml/issues/480
This attempts to support a special 'wildcard' schema element, called by default "xs_any", that will match any unmatched XML elements in a node, and treat them as strings containing the raw XML content. If it's a string, it will match one element. If it's an array of strings, it will match all of them.
This provides a natural interpretation of "xs:any" in XSDs then.
> Support xs:any in XSD as a 'wildcard' schema element in XML parser

- README.md
- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtils.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/test/resources/books-namespaces.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
This adds a new `ignoreNamespace` parameter that will disregard namespace prefixes on elements (besides the root tag)
Closes #168
> Add option to ignore namespace on elements

- src/main/scala/com/databricks/spark/xml/util/XmlFile.scala
Closes #510 
Use Text.toString to retrieve String from XmlInputFormat. This ensures that it isn't treated as UTF-8 when that isn't the configured encoding.
> Use Text.toString to get Strings from XmlInputFormat

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/resources/struct_with_optional_child.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
> Fix parsing of array-valued struct field with an optional child element; misparsed when struct element is entirely empty

- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
These constants were not really serving much purpose and made some test logic harder to read. Just some cleanup.
> Remove fairly redundant constant declaration idiom in test file

- README.md
- build.sbt
- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/main/scala/com/databricks/spark/xml/util/TypeCast.scala
- src/test/resources/date.xml
- src/test/resources/time.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
- src/test/scala/com/databricks/spark/xml/util/TypeCastSuite.scala
Closes #519 . This adds support for `dateFormat`, `timestampFormat` options when reading/writing, and generally improves the consistency of inference and parsing.
> Add dateFormat, timestampFormat support

- project/build.properties
- src/main/scala/com/databricks/spark/xml/XmlReader.scala
- src/main/scala/com/databricks/spark/xml/package.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Closes #527.
See #527 for discussion of the issue.
> Deprecate Dataset[String] implicit, and XmlReader.withX setters. Add options / schema param to XmlReader constructor.

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
**Before this PR:** the attached test would crash because we're not providing a valueTag in our struct schema. This is a regression from a previous version, where this was simply ignored.
**After this PR:** character element is ignored instead when there is no value tag.
> Fix missing value tag crash

- .github/workflows/test_spark_2_java_8.yml
- .github/workflows/test_spark_3_java_11.yml
This PR proposes to use:
- static branches instead of `$default-branch` that's to be used as a template.
- use `adopt@1.8` syntax (as documented in https://github.com/olafurpg/setup-scala). Otherwise it picks JDK 11 for `java-version: '8'`.
> Change $default_branch to static branches (and set Java version correctly)

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
Unsupported elements in XSDs lead to scala MatchError, without detail. This just throws an exception with some clue about what was not matched in several places.
> Improve error reporting for unsupported XSD elements

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
Pretty much as it says. This supports cases like:
```
<xs:complexType name="foo">
<xs:attribute name="bar" type="bing" use="required"/>
<xs:attribute name="baz" type="buzz" use="required"/>
</xs:complexType>
```
and
```
<xs:complexType name="foo">
<xs:attribute name="bar" fixed="X" use="required"/>
</xs:complexType>
```
> Support XSD schema complexType with only attributes; with value but no type too (assume string)

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtils.scala
- src/test/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtilsSuite.scala
Relates to https://github.com/databricks/spark-xml/issues/562.
Doesn't really make spark-xml more secure but may still be worth adding from an abundance of caution.
> disable DTD parsing (just in case)

- README.md
- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Per https://github.com/databricks/spark-xml/issues/570 , allow empty attributePrefix on reading only, to not prefix attribute-based fields in the resulting DataFrame
> Allow empty attributePrefix on read only

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/decimal-with-restriction.xsd
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
This code fix is for XSD having the decimal data type with restriction. XSDToSchema util class returns the StringType if the XSD has the decimal data type with restriction.
> Fix is for XSD having the decimal data type with restriction

- .gitignore
- build.sbt
- project/build.properties
- Updated .gitignore to ignore files/folders specific to VS Code Scala Metals
- Updated build.properties
- Minor refactoring to build.sbt to conform to slash syntax
> Upgrade SBT

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtils.scala
- src/test/resources/mixed_children_as_string.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
> Simplify handling of complex mixed elements when schema says it is a string; should always just repeat the content as string

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/complex-content-extension.xsd
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
Resolves an issue reported in https://github.com/databricks/spark-xml/issues/554
- adding the capability to parse extension element in complexContent
> Parse complexContent with extension element

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/resources/feed-with-spaces.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
At some point, strings stopped going through the convertTo() path, and that's what handles ignoreSurroundingSpaces.
Fixes https://github.com/databricks/spark-xml/issues/636
> Restore functionality of ignoreSurroundingSpaces when field is a simple string

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/decimal-with-restriction.xsd
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
Two things:
Support frac digits, not just scale, in XSD schemas when reading XSDs as schema.
Also, try to support simple named types in the XSD along the way.
> In XSD, handle frac digits for decimal types. Also try to support custom type declarations in the XSD

- src/main/scala/com/databricks/spark/xml/util/TypeCast.scala
- src/test/scala/com/databricks/spark/xml/util/TypeCastSuite.scala
Closes https://github.com/databricks/spark-xml/issues/643
> Disallow strings ending in D or F as doubles when inferring schema

- src/main/scala/com/databricks/spark/xml/util/TypeCast.scala
In schema inference, many different types are tried out for each input. This can get really slow in some cases, especially where the true type is just 'string'. This adds several shortcuts in the type inference code, to fail fast before expensive parsing code is run, where it's clear the parsing won't work. This also avoids using a thrown exception in one case for better speed.
> Shortcut common type inference cases to fail fast, speed up inference
