- CONTRIBUTING.md
To be complete we should explicitly state the licensing of any contributions to the project
> Add statement about licensing of contributions

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/test/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtilsSuite.scala
> Use JavaConverters instead of deprecated JavaConversions

- README.md
- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/main/scala/com/databricks/spark/xml/XmlRelation.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/main/scala/com/databricks/spark/xml/util/XmlFile.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
- src/test/scala/com/databricks/spark/xml/parsers/StaxXmlParserUtilsSuite.scala
- src/test/scala/com/databricks/spark/xml/util/XmlFileSuite.scala
Don't round-trip convert XML to bytes and back in parser; other misc refinements
> Don't round-trip convert XML to bytes and back in parser

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlGenerator.scala
- src/test/resources/books-complicated-null-attribute.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
This supersedes https://github.com/databricks/spark-xml/pull/336
This also partially resolves https://github.com/databricks/spark-xml/pull/247
> Fix null attribute in XML write

- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
> Apply some optimizations from SPARK-14972 to improve inference speed

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/resources/null-empty-string.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
See https://github.com/databricks/spark-xml/commit/1c24c9c6e2812470bae3b6c6caab7ec518bf84eb#r32431854
> Also treat empty values as null if the nullValue is "", where it is checked earlier

- .travis.yml
- README.md
- build.sbt
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- Update to latest maintenance releases of Spark
- Update spark-xml version
- Stop testing vs Spark 2.2
- Misc tweaks from inspection
> Update Spark versions, update spark-xml version. Misc small tweaks.

- src/main/scala/com/databricks/spark/xml/package.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
> Add schema_of_xml_df for Python future use

- README.md
See https://github.com/databricks/spark-xml/issues/435
> Add note about how to wrap functions from Pyspark

- build.sbt
- dev/make-release.sh
(This may not pass checks until 0.9.0 hits all the mirrors)
> Update next version to 0.10.0; update MiMa; fix some typos

- README.md
- src/main/scala/com/databricks/spark/xml/util/XmlFile.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
> Add basic support for attributes on root tag that is written

- build.sbt
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/test/resources/map-attribute.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
> Add element attributes to map result when schema specifies MapType

- build.sbt
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/main/scala/com/databricks/spark/xml/util/TypeCast.scala
- src/test/resources/date.xml
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
(This is related to #519 but not its resolution)
> Fix type inference for Dates; code cleanup

- .travis.yml
- build.sbt
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
Includes a small fix to accommodate updated XML parser (?) in Hadoop 3+
> Test vs Spark 3.1 and drop 2.3

- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
Helps clarify the problem arising in #532
> Prohibit < and > in rowTag, rootTag

- src/main/scala/com/databricks/spark/xml/XmlOptions.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
I am not a scala programmer .. but based on what I see in this file .. and the build error .. this might solve it
> fix line length build error + add additional tests

- README.md
- src/main/scala/com/databricks/spark/xml/package.scala
> Fix avro -> XML typo; update README

- README.md
- src/main/scala/com/databricks/spark/xml/XmlReader.scala
- src/main/scala/com/databricks/spark/xml/package.scala
- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
- src/main/scala/com/databricks/spark/xml/util/InferSchema.scala
- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/main/scala/com/databricks/spark/xml/util/XmlFile.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
- src/test/scala/com/databricks/spark/xml/parsers/StaxXmlGeneratorSuite.scala
Miscellaneous changes to fix compatibility with Scala 2.13, and reduce warnings in 2.13
> Changes for scala 2.13 compatibility later

- src/main/scala/com/databricks/spark/xml/XmlRelation.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
> Tickle underlying RDD of XML's partitions to ensure files are checked for existence in all cases

- src/main/scala/com/databricks/spark/xml/parsers/StaxXmlParser.scala
Original issue at https://github.com/databricks/spark-xml/issues/593 but was somehow deleted?
The ideas here are to:
- Not put the data in the exception message, but stick to logs, to maybe avoid data leakage to caller
- Standardize and rationalize how these are logged
> Rationalize logging of record, exception in error cases

- src/main/scala/com/databricks/spark/xml/util/XSDToSchema.scala
- src/test/resources/ref-attribute.xsd
- src/test/scala/com/databricks/spark/xml/util/XSDToSchemaSuite.scala
Resolves #617 
- adding the capability to parse ref attribute
> Parse ref attribute in XSD element 

- src/main/scala/com/databricks/spark/xml/util/TypeCast.scala
- src/test/scala/com/databricks/spark/xml/XmlSuite.scala
- src/test/scala/com/databricks/spark/xml/util/TypeCastSuite.scala
> Handle decimals with scale greater than precision

- README.md
> Note plan to merge spark-xml to Apache Spark 4.0
